[[main]]
name = "Home"
url = "/"
weight = 1
pre = "iconfont icon-home-fill"

[[main]]
name = "Archives"
url = "/archives/"
weight = 2
pre = "iconfont icon-archive-fill"

[[main]]
name = "Categories"
url = "/categories/"
weight = 3
pre = "iconfont icon-category-fill"

[[main]]
name = "Tags"
url = "/tags/"
weight = 4
pre = "iconfont icon-tags-fill"

[[main]]
name = "Links"
url = "/links/"
weight = 5
pre = "iconfont icon-link-fill"

[[main]]
name = "About"
url = "/about/"
weight = 6
pre = "iconfont icon-user-fill"

# Documentation dropdown menu
[[main]]
name = "Docs"
url = "/docs/"
weight = 7
pre = "iconfont icon-books"
hasChildren = true

[[main]]
name = "Quick Start"
url = "/docs/"
weight = 71
parent = "Docs"

[[main]]
name = "Configuration"
url = "/docs/config/"
weight = 72
parent = "Docs"

[[main]]
name = "Features"
url = "/docs/features/"
weight = 73
parent = "Docs"

[[main]]
name = "Dropdown Menu Config"
url = "/docs/dropdown-menu/"
weight = 74
parent = "Docs"
